global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node_api"
    static_configs:
      - targets: ["backend:5000"]
    metrics_path: /metrics/

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]